### ISSUE TITLE
preview hangs

### ISSUE THREAD

**Issue by techtonik** [arc90/git-sweep#29]
Hangs indefinitely. Is there a way to debug this?
```
Fetching from the remote
Traceback (most recent call last):
  ...
    CommandLine(sys.argv).run()
  File "C:\Python27\lib\site-packages\gitsweep\cli.py", line 89, in run
    self._sweep()
  File "C:\Python27\lib\site-packages\gitsweep\cli.py", line 126, in _sweep
    ok_to_delete = inspector.merged_refs(skip=skips)
  File "C:\Python27\lib\site-packages\gitsweep\inspector.py", line 37, in merged_refs
    with_extended_output=True, with_exceptions=False)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 346, in execute
    stdout_value, stderr_value = proc.communicate()
  File "C:\Python27\lib\subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "C:\Python27\lib\subprocess.py", line 1043, in _communicate
    stdout_thread.join()
  File "C:\Python27\lib\threading.py", line 949, in join
    self.__block.wait()
  File "C:\Python27\lib\threading.py", line 339, in wait
    waiter.acquire()
  File "C:\Python27\lib\site-packages\async\__init__.py", line 21, in thread_interrupt_handler
    prev_handler(signum, frame)
KeyboardInterrupt
```

**Comment by techtonik** [comment]
git-sweep executes `git cherry origin/master origin/1.0` on https://github.com/wesnoth/wesnoth/ repository, which is 2.1Gb.

**Comment by techtonik** [comment]
https://stackoverflow.com/questions/18201293/why-is-git-cherry-so-astonishingly-slow

I thought that `git-sweep` will just execute `git branches` and attempt to do `git branch -d <branchname>` on them.

**Comment by TheBuzzSaw** [comment]
I have this problem too. Running a preview just sits there forever. Is there a workaround/fix?
