### ISSUE TITLE
I get this error when running bootstrap.py

### ISSUE THREAD

**Issue by joshua-lucier** [arc90/git-sweep#35]
I get this error when running bootstrap.py

Traceback (most recent call last):
  File "bootstrap.py", line 58, in <module>
    ).read() in ez
  File "<string>", line 1
    <!DOCTYPE html>
    ^

It looks like the links that the url requests are asking for may be dead.  

http://python-distribute.org/distribute_setup.py

**Comment by dpaparis** [comment]
same here

**Comment by xuanyuan** [comment]
nobody who knows how to fix it?

**Comment by hyunchel** [comment]
Python distribute is long dead. The website has been down for a long time too.
Use `setuptools` instead. 

Change default value of option `--distribute` to `False`(line-number 34). and run without `--distribute` flag.

No PR should be pushed as there is no plan to maintain this project(#43).
